---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```


```{r, message = FALSE, warning = FALSE}
data("ny_noaa")

ny_noaa = ny_noaa %>%
  separate(date, c("year", "month", "day")) %>% 
  mutate(across(year:tmin,as.numeric),
         tmax = tmax / 10,
         tmin = tmin / 10) %>% 
  drop_na()
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
ny_noaa %>%
  filter(id == "USC00303346",
         between(snow,0,100), !is.na(snow)) %>% 
  mutate(text_label = str_c("Year: ", year, "\nSnow Depth: ", snow, "mm")) %>% 
  plot_ly(y = ~snow, x = ~year, color = ~month, text = ~text_label,
          type = "scatter", colors = "viridis", mode = "markers")%>%   
  layout(title = "Snow Distribution for Station USC00303346 from 1981-2010",
             xaxis = list(title = "Year"), yaxis = list(title = "Snow Depth"))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
ny_noaa %>% 
  filter(month == 3) %>% 
  group_by(year, id) %>% 
  summarize(avg_tmax = mean(tmax)) %>% 
  drop_na() %>% 
  plot_ly(y = ~avg_tmax, x = ~year, color = ~id,
          type = "violin", colors = "viridis") %>%   
  layout(title = "Average Max Temp for Each Sation in March from 1981-2010",
         xaxis = list(title = "Year"), yaxis = list(title = "Average Max Temp"))
```

### Chart C

```{r}
ny_noaa %>% 
  filter(month == 9) %>% 
  group_by(year, id) %>% 
  summarize(avg_tmax = mean(tmax)) %>% 
  drop_na() %>% 
  plot_ly(y = ~avg_tmax, x = ~year, color = ~id,
          type = "violin", colors = "viridis") %>%   
  layout(title = "Average Max Temp for Each Sation in September from 1981-2010",
         xaxis = list(title = "Year"), yaxis = list(title = "Average Max Temp" ))
```

